services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-kelas-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    entrypoint: ["/var/www/docker-entrypoint.sh"]
  mysql:
    image: mysql:8.0
    container_name: web-kelas-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: web_kelas_elektro
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-kelas-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
volumes:
  mysql_data: